---
#Escriba la definición de su playbook, los hosts sobre los que se ejecutará, que realice escalamiento de privilegios y que obtenga facts.
- hosts: node1
  name: Prueba Linux
  become: true
  gather_facts: true
  
  tasks:
#Instale los paquetes necesarios para correr PostgreSQL
  - name: Install Postgress
    ansible.builtin.yum:
      name:
        - postgresql
        - postgresql-server
      state: present

#Inicialice PostgreSQL           
  - name: Find out if PostgreSQL is initialized
    ansible.builtin.stat:
      path: "/var/lib/pgsql/data/pg_hba.conf"
    register: postgres_data
      
  - name: "Initialize PostgreSQL"
    shell: "postgresql-setup initdb"
    when: not postgres_data.stat.exists
      
#Asegúrese de que los servicios de PostgreSQL se encuentren habilitados y activos

  - name: Enable service httpd, and not touch the state
    ansible.builtin.service:
      name: postgresql
      enabled: yes
      state: started
      
#Asegúrese de que los servicios de PostgreSQL se encuentren habilitados y activos
  #handlers:
    #- name: restart_postgresql
      #service:
        #name: postgresql
        #state: restarted
#Cree una base de datos
  - name: Create  database
    community.postgresql.postgresql_db:
      state: present
      name: db_marcopparco
        
#Cree un usuario de base de datos
  - name: "Create db user"
    community.postgresql.postgresql_user:
      state: present
      name: marco
      password: marcoparco




