---
#Escriba la definición de su playbook, los hosts sobre los que se ejecutará, que realice escalamiento de privilegios y que obtenga facts.
- hosts: node1
  name: Prueba Linux
  become: true
  gather_facts: true
  
  tasks:    
 #Cambie el hostname de la máquina
    - name: Set a hostname
      ansible.builtin.hostname:
        name: marcolocalhost
        
    - name: Get IP address remote server
      debug:
        
   


        




