---
#Escriba la definición de su playbook, los hosts sobre los que se ejecutará, que realice escalamiento de privilegios y que obtenga facts.
- hosts: node1
  name: Prueba Linux
  become: true
  gather_facts: true
  
  tasks:
#Instale los paquetes necesarios para correr PostgreSQL
  - name: Install Postgress
    ansible.builtin.yum:
      name:
        - postgresql
        - postgresql-server
      state: present
      
#Inicialice PostgreSQL     
  - name: Enable service postgresql-server
    ansible.builtin.service:
      name: postgres
      state: started
      
#Asegúrese de que los servicios de PostgreSQL se encuentren habilitados y activos
  - name: Enable service httpd, and not touch the state
    ansible.builtin.service:
      name: postgres
      enabled: yes
      state: started



